# Generated by Django 4.0.2 on 2022-02-28 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagerabbit_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='start_date',
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.CharField(max_length=600)),
                ('dates', models.CharField(max_length=150)),
                ('venue', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagerabbit_app.theater')),
            ],
        ),
    ]
