# Generated by Django 4.0.2 on 2022-02-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagerabbit_app', '0002_remove_theater_end_date_remove_theater_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='zip',
            field=models.CharField(default='', max_length=20),
        ),
    ]
