# Generated by Django 4.0.2 on 2022-03-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagerabbit_app', '0004_alter_production_dates_alter_production_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='dates',
        ),
        migrations.AddField(
            model_name='production',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
