# Generated by Django 4.0.2 on 2022-03-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stagerabbit_app', '0005_remove_production_dates_production_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'verbose_name': {'theater'}},
        ),
    ]
