# Generated by Django 4.0.2 on 2022-03-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stagerabbit_app', '0007_alter_production_theater'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={},
        ),
    ]
