# Generated by Django 4.0.4 on 2022-04-23 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagerabbit_app', '0008_alter_production_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14)),
                ('abbr', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='theater',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
