# Generated by Django 4.0.4 on 2022-04-23 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagerabbit_app', '0009_statename_alter_theater_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='zip',
        ),
        migrations.AlterField(
            model_name='theater',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='stagerabbit_app.statename'),
        ),
    ]
