# Generated by Django 4.0.4 on 2022-04-26 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stagerabbit_app', '0010_remove_theater_zip_alter_theater_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StateName',
            new_name='State',
        ),
    ]
